apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
     env: demo
     tier: front-end
spec:
  containers:
    - name: nginx-pod
      image: nginx
      ports:
        - containerPort: 80